name: Build, Test

on: [push]

jobs:
  test-ui:
    name: Test UI
    runs-on: ubuntu-latest
    container: cypress/base:14.17.3

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test:ci
      - name: Fix paths
        run: |
          sed -i 's@../angular@/github/workspace/angular@g' cypress/.results/lcov.info
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
